name = "GithubSatcomRegistry"
uuid = "c7468e3b-2b83-469b-8010-9ae319e284b9"
repo = "https://github.com/JuliaSatcomFramework/JuliaRegistry.git"

[packages]
13e19751-ccd1-416d-be0c-a6724a8caa31 = { name = "BasicTypes", path = "B/BasicTypes" }
17778021-2b2c-4ecf-610a-391273688f7f = { name = "ITUPropagationModels", path = "I/ITUPropagationModels" }
22c7c615-cf67-4787-b800-cc81b4f1a63f = { name = "GeoGrids", path = "G/GeoGrids" }
378a5cb6-73fb-4189-b384-0a829fc08157 = { name = "SequentialOutputChannels", path = "S/SequentialOutputChannels" }
61f21f9a-4073-5473-9260-49250f3db370 = { name = "PlutoShowHelpers", path = "P/PlutoShowHelpers" }
6f00a2c5-ea4a-46bf-9183-91b7b57a087f = { name = "SimplePlutoInclude", path = "S/SimplePlutoInclude" }
a0499f29-c39b-4c5c-807c-88074221b949 = { name = "PlutoDevMacros", path = "P/PlutoDevMacros" }
a73e506c-35e8-47b2-857c-dfce7ead1349 = { name = "ItuRPropagation", path = "I/ItuRPropagation" }
a7e57fc7-3548-4021-90c3-ac0e175068b1 = { name = "PlotlyExtensionsHelper", path = "P/PlotlyExtensionsHelper" }
c20ae07a-79b5-4dbd-b2dc-f2e51386613e = { name = "GeoPlottingHelpers", path = "G/GeoPlottingHelpers" }
eb248270-a497-541c-8f75-6bb2aa2715dc = { name = "ExtendedLocalCoverage", path = "E/ExtendedLocalCoverage" }
ee40d4b5-31c3-4fe2-b6cc-5ac7adf7f414 = { name = "CountriesBorders", path = "C/CountriesBorders" }
